// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnkfxespnkoguipzthbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFua2Z4ZXNwbmtvZ3VpcHp0aGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTkxOTUsImV4cCI6MjA2OTA3NTE5NX0.FM_jDhqhhfRrfX6wHsAGfIPe66jG0XDxc8eLVHqyCGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});